### PR TITLE
Added polarity Annotation

### PR DESCRIPTION
**Pull request by KennethEnevoldsen**
Added polarity annotation in accordance with the Swedish UDT.

Generally it is a pattern match on ikke (lemma) + ADV, aldrig (lemma) + ADV, næppe (lemma) + ADV. With a few exceptions for aldrig (which I am a bit unsure about). Some of these include: test-132, test2-185, and train-v2-2013

The reason why I want to add it is that packages such as [Asent](https://kennethenevoldsen.github.io/asent/customizing.html) can utilize it, and when training, introducing spelling errors can lead to better (more robust) analysis than a simple rule-based approach.

@dan-zeman and @jnivre would love to have an extra pair of eyes on this if you have the time.

### CODE REVIEW

**Comment by dan-zeman** [comment]
Adding `Polarity=Neg` to all instances of _ikke_ seems pretty uncontroversial to me. But my standard complaint is that you cannot pick the master branch as the target of a pull request.

**Comment by KennethEnevoldsen** [comment]
Sorry my bad. Keep forgetting. Any way to turn that option off in settings?

**Comment by dan-zeman** [comment]
> Sorry my bad. Keep forgetting. Any way to turn that option off in settings?

That does not seem possible, unfortunately.

It would be possible to make `dev` the default target branch for new PRs. But it would mean that the `dev` branch is set as the default branch of every treebank repository. And that would go against the main reason why the current branch logic was introduced in UD: People who somehow land at one of the treebank repositories should by default see the data that were part of the latest official release, i.e., the `master` branch.

**Comment by jnivre** [comment]
I agree with Dan. I had a look at the sentences you mention as exceptions, but I didn't see any reason not to add the feature Polarity=Neg to "aldrig" in these sentences, so I think you can just go ahead and add the feature by pattern matching (but commit to the dev branch).

**Pull request merged**
